// Mentalita — Central de Faturamento
// Fases 1–5: guias, lotes, recebimentos, retificações e glosas.
(function(){
'use strict';
if(window.__mentalitaFaturamentoV2)return;
window.__mentalitaFaturamentoV2=true;
const S=()=>window.PLURI_SUPABASE||null,C=()=>window.PLURI_CLINIC?.id||null,U=()=>window.PLURI_AUTH_SESSION?.user?.id||null;
let activeTab='visao',busy=false;
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v||0));
const date=v=>v?new Date(String(v).slice(0,10)+'T00:00:00').toLocaleDateString('pt-BR'):'—';
const dateTime=v=>v?new Date(v).toLocaleString('pt-BR'):'—';
const esc=v=>String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
const guideLabels={draft:'Rascunho',ready:'Pronta para faturamento',batched:'Em lote',sent:'Enviada',processed:'Processada',paid:'Recebida'};
const receiptLabels={received:'Recebido',pending:'Pendente',cancelled:'Cancelado'};
const denialLabels={open:'Em aberto',resolved:'Resolvida'};
const gl=v=>guideLabels[v]||v||'—',rl=v=>receiptLabels[v]||v||'—',dl=v=>denialLabels[v]||v||'—';
async function rows(table,order='created_at'){const c=S(),clinic=C();if(!c||!clinic)throw Error('Clínica não identificada.');const r=await c.from(table).select('*').eq('clinic_id',clinic).order(order,{ascending:false});if(r.error)throw r.error;return r.data||[];}
const guides=()=>rows('mentalita_patient_tiss_guides'),lots=()=>rows('mentalita_billing_lots'),receipts=()=>rows('mentalita_billing_receipts'),denials=()=>rows('mentalita_billing_denials');
async function patientNames(ids){const u=[...new Set((ids||[]).filter(Boolean))];if(!u.length)return{};const r=await S().from('mentalita_patients').select('id,name').in('id',u);if(r.error)throw r.error;return Object.fromEntries((r.data||[]).map(x=>[x.id,x.name]));}
async function lotLinks(ids){if(!ids.length)return[];const r=await S().from('mentalita_billing_lot_guides').select('lot_id,guide_id').in('lot_id',ids);if(r.error)throw r.error;return r.data||[];}
function tabs(){return `<div class="billing-tabs">${[['visao','Visão geral'],['guias','Guias prontas'],['lotes','Lotes'],['glosas','Glosas'],['recebimentos','Recebimentos']].map(([id,t])=>`<button type="button" class="btn billing-tab ${activeTab===id?'active':''}" data-billing-tab="${id}">${t}</button>`).join('')}</div>`;}
function overview(gs,ls,rs,ds){const ready=gs.filter(x=>x.status==='ready'),open=ls.filter(x=>['draft','processed'].includes(x.status)).reduce((a,x)=>a+Number(x.total_amount||0),0),sent=ls.filter(x=>x.status==='sent').reduce((a,x)=>a+Number(x.total_amount||0),0),received=rs.filter(x=>x.status==='received').reduce((a,x)=>a+Number(x.amount||0),0),denied=ds.filter(x=>x.status!=='resolved').reduce((a,x)=>a+Number(x.amount||0),0);return `<div class="billing-shell"><div class="billing-kpis"><div class="billing-kpi"><small>Guias prontas</small><strong>${ready.length}</strong><span>${money(ready.reduce((a,x)=>a+Number(x.total_amount||0),0))}</span></div><div class="billing-kpi"><small>Em aberto</small><strong>${money(open)}</strong><span>${ls.filter(x=>['draft','processed'].includes(x.status)).length} lotes</span></div><div class="billing-kpi"><small>Enviado</small><strong>${money(sent)}</strong><span>${ls.filter(x=>x.status==='sent').length} lotes</span></div><div class="billing-kpi"><small>Recebido</small><strong>${money(received)}</strong><span>${rs.filter(x=>x.status==='received').length} recebimentos</span></div><div class="billing-kpi"><small>Glosado em aberto</small><strong>${money(denied)}</strong><span>${ds.filter(x=>x.status!=='resolved').length} glosas</span></div></div><div class="billing-card"><div class="billing-head"><div><h3>Fluxo de faturamento</h3><p>Guia → lote → envio → recebimento → glosa.</p></div></div><div class="billing-flow"><div class="billing-stage"><small>01</small><strong>Guias</strong><span>${gs.length} registros</span></div><div class="billing-stage"><small>02</small><strong>Lotes</strong><span>${ls.length} lotes</span></div><div class="billing-stage"><small>03</small><strong>Financeiro</strong><span>${rs.length} recebimentos · ${ds.length} glosas</span></div></div></div></div>`;}
function guideRow(g,names,ready){return `<div class="billing-row"><div class="billing-main">${ready?`<input class="billing-check" type="checkbox" data-guide-check value="${esc(g.id)}">`:''}<div><strong>${esc(names[g.patient_id]||'Paciente')}</strong><div class="billing-note">Guia ${esc(g.guide_number||'sem número')} · ${date(g.execution_date)} · ${money(g.total_amount)}</div></div></div><div class="billing-actions"><span class="billing-status">${esc(gl(g.status))}</span>${!ready&&g.status==='draft'?`<button type="button" class="btn" data-release-guide="${esc(g.id)}">Liberar para faturamento</button>`:''}</div></div>`;}
function guidesView(gs,names){const ready=gs.filter(x=>x.status==='ready'),drafts=gs.filter(x=>x.status==='draft');return `<div class="billing-shell"><div class="billing-card"><div class="billing-head"><div><h3>Guias prontas para faturamento</h3><p>Selecione somente guias liberadas para formar um lote.</p></div><button type="button" class="btn" data-create-lot ${ready.length?'':'disabled'}>Criar lote</button></div><div class="billing-list">${ready.length?ready.map(x=>guideRow(x,names,true)).join(''):'<div class="billing-empty">Nenhuma guia pronta para faturamento.</div>'}</div></div><div class="billing-card"><div class="billing-head"><div><h3>Guias em preparação</h3><p>Rascunhos criados na ficha do paciente. Nenhuma guia é liberada automaticamente.</p></div></div><div class="billing-list">${drafts.length?drafts.map(x=>guideRow(x,names,false)).join(''):'<div class="billing-empty">Nenhum rascunho pendente.</div>'}</div></div></div>`;}
function lotsView(ls,links,gs){const gm=Object.fromEntries(gs.map(x=>[x.id,x])),by={};links.forEach(x=>(by[x.lot_id]??=[]).push(x.guide_id));return `<div class="billing-shell"><div class="billing-card"><div class="billing-head"><div><h3>Lotes</h3><p>Lotes criados a partir de guias prontas para faturamento.</p></div></div><div class="billing-list">${ls.length?ls.map(l=>`<div class="billing-row"><div><strong>${esc(l.lot_number||'Lote sem número')}</strong><div class="billing-note">${l.guide_count||0} guia(s) · ${money(l.total_amount)} · criado em ${dateTime(l.created_at)}</div><div class="billing-note">Guias: ${(by[l.id]||[]).map(id=>esc(gm[id]?.guide_number||id)).join(', ')||'—'}</div></div><div class="billing-actions"><span class="billing-status">${esc(gl(l.status))}</span>${l.status==='draft'?`<button type="button" class="btn" data-submit-lot="${esc(l.id)}">Enviar lote</button>`:''}</div></div>`).join(''):'<div class="billing-empty">Nenhum lote criado.</div>'}</div></div></div>`;}
function receiptsView(rs,ls){return `<div class="billing-shell"><div class="billing-card"><div class="billing-head"><div><h3>Recebimentos</h3><p>Registre valores recebidos e vincule-os ao lote quando houver.</p></div><button type="button" class="btn" data-new-receipt>Novo recebimento</button></div><div class="billing-list">${rs.length?rs.map(r=>`<div class="billing-row"><div><strong>${money(r.amount)}</strong><div class="billing-note">${date(r.received_at)} · ${r.reference?`Ref. ${esc(r.reference)} · `:''}${r.lot_id?`Lote ${esc(ls.find(l=>l.id===r.lot_id)?.lot_number||r.lot_id)}`:'Sem lote'}</div>${r.notes?`<div class="billing-note">${esc(r.notes)}</div>`:''}</div><div class="billing-actions"><span class="billing-status">${esc(rl(r.status))}</span>${r.status==='received'?`<button type="button" class="btn" data-retify-receipt="${esc(r.id)}">Retificar</button>`:''}</div></div>`).join(''):'<div class="billing-empty">Nenhum recebimento registrado.</div>'}</div></div></div>`;}
function glosasView(ds,ls,gs){const names=Object.fromEntries(gs.map(g=>[g.id,g]));return `<div class="billing-shell"><div class="billing-card"><div class="billing-head"><div><h3>Glosas</h3><p>Registre recusas e acompanhe a resolução sem apagar o histórico.</p></div><button type="button" class="btn" data-new-denial>+ Registrar glosa</button></div><div class="billing-list">${ds.length?ds.map(d=>`<div class="billing-row"><div><strong>${money(d.amount)}</strong><div class="billing-note">${d.guide_id?`Guia ${esc(names[d.guide_id]?.guide_number||d.guide_id)} · `:''}${d.lot_id?`Lote ${esc(ls.find(l=>l.id===d.lot_id)?.lot_number||d.lot_id)} · `:''}${dateTime(d.created_at)}</div><div class="billing-note">${esc(d.reason||'Sem motivo')}</div>${d.notes?`<div class="billing-note">${esc(d.notes)}</div>`:''}</div><div class="billing-actions"><span class="billing-status">${esc(dl(d.status))}</span>${d.status!=='resolved'?`<button type="button" class="btn" data-resolve-denial="${esc(d.id)}">Resolver</button>`:''}<button type="button" class="btn" data-retify-denial="${esc(d.id)}">Retificar</button></div></div>`).join(''):'<div class="billing-empty">Nenhuma glosa registrada.</div>'}</div></div></div>`;}
function modalWrap(title,body){return `<div class="billing-modal-backdrop" data-billing-modal><div class="billing-modal"><div class="billing-head"><div><h3>${title}</h3></div><button type="button" class="btn" data-close-billing-modal>Cancelar</button></div>${body}</div></div>`;}
function receiptModal(ls){return modalWrap('Novo recebimento',`<div class="billing-form"><div class="billing-field"><label>Lote</label><select id="receiptLot"><option value="">Sem lote</option>${ls.map(l=>`<option value="${esc(l.id)}">${esc(l.lot_number||'Lote sem número')} · ${money(l.total_amount)}</option>`).join('')}</select></div><div class="billing-field"><label>Data do recebimento</label><input id="receiptDate" type="date" value="${new Date().toISOString().slice(0,10)}"></div><div class="billing-field"><label>Valor recebido</label><input id="receiptAmount" type="number" min="0" step="0.01"></div><div class="billing-field"><label>Referência</label><input id="receiptReference" maxlength="200"></div><div class="billing-field full"><label>Observações</label><textarea id="receiptNotes"></textarea></div><div class="billing-form-actions"><button type="button" class="btn" data-save-receipt>Salvar recebimento</button></div></div>`);}
function retifyModal(r){return modalWrap('Retificar recebimento',`<div class="billing-form"><div class="billing-field"><label>Data</label><input id="retifyDate" type="date" value="${esc(String(r.received_at||'').slice(0,10))}"></div><div class="billing-field"><label>Valor</label><input id="retifyAmount" type="number" min="0" step="0.01" value="${esc(r.amount)}"></div><div class="billing-field full"><label>Referência</label><input id="retifyReference" maxlength="200" value="${esc(r.reference||'')}"></div><div class="billing-field full"><label>Observações</label><textarea id="retifyNotes">${esc(r.notes||'')}</textarea></div><div class="billing-field full"><label>Motivo da retificação *</label><textarea id="retifyReason" required></textarea></div><input id="retifyId" type="hidden" value="${esc(r.id)}"><div class="billing-form-actions"><button type="button" class="btn" data-save-retification>Salvar retificação</button></div></div>`);}
function denialModal(ls,gs,d=null){const edit=!!d;return modalWrap(edit?'Retificar glosa':'Registrar glosa',`<div class="billing-form"><div class="billing-field"><label>Lote</label><select id="denialLot"><option value="">Sem lote</option>${ls.map(l=>`<option value="${esc(l.id)}" ${d?.lot_id===l.id?'selected':''}>${esc(l.lot_number||'Lote sem número')} · ${money(l.total_amount)}</option>`).join('')}</select></div><div class="billing-field"><label>Guia</label><select id="denialGuide"><option value="">Sem guia</option>${gs.map(g=>`<option value="${esc(g.id)}" ${d?.guide_id===g.id?'selected':''}>${esc(g.guide_number||'Guia sem número')} · ${money(g.total_amount)}</option>`).join('')}</select></div><div class="billing-field"><label>Valor glosado</label><input id="denialAmount" type="number" min="0" step="0.01" value="${d?esc(d.amount):''}"></div><div class="billing-field"><label>Motivo</label><input id="denialReason" maxlength="300" value="${esc(d?.reason||'')}"></div><div class="billing-field full"><label>Observações</label><textarea id="denialNotes">${esc(d?.notes||'')}</textarea></div>${edit?`<div class="billing-field full"><label>Motivo da retificação *</label><textarea id="denialRevisionReason" required></textarea><input id="denialRevisionId" type="hidden" value="${esc(d.id)}"></div>`:''}<div class="billing-form-actions"><button type="button" class="btn" data-save-denial ${edit?'data-edit-denial="1"':''}>${edit?'Salvar retificação':'Registrar glosa'}</button></div></div>`);}
function resolveModal(d){return modalWrap('Resolver glosa',`<div class="billing-form"><div class="billing-field"><label>Valor recuperado</label><input id="resolveRecovered" type="number" min="0" step="0.01" value="${esc(d.recovered_amount||0)}"></div><div class="billing-field full"><label>Observações da resolução</label><textarea id="resolveNotes">${esc(d.notes||'')}</textarea></div><input id="resolveId" type="hidden" value="${esc(d.id)}"><div class="billing-form-actions"><button type="button" class="btn" data-save-resolution>Resolver glosa</button></div></div>`);}
async function render(){const host=document.getElementById('billingWorkspace');if(!host||busy)return;busy=true;host.innerHTML='<div class="billing-card"><div class="billing-empty">Carregando faturamento…</div></div>';try{const[gs,ls,rs,ds]=await Promise.all([guides(),lots(),receipts(),denials()]);const names=await patientNames(gs.map(g=>g.patient_id));let body=overview(gs,ls,rs,ds);if(activeTab==='guias')body=guidesView(gs,names);if(activeTab==='lotes')body=lotsView(ls,await lotLinks(ls.map(l=>l.id)),gs);if(activeTab==='recebimentos')body=receiptsView(rs,ls);if(activeTab==='glosas')body=glosasView(ds,ls,gs);host.innerHTML=`<div class="billing-shell">${tabs()}${body}</div>`;}catch(e){console.error('[Mentalita Faturamento]',e);host.innerHTML=`<div class="billing-card billing-error"><h3>Erro ao carregar Faturamento</h3><pre>${esc(e?.message||e)}</pre></div>`;}finally{busy=false;}}
async function releaseGuide(id){const c=S(),clinic=C();const g=(await guides()).find(x=>x.id===id);if(!c||!clinic||!g)throw Error('Guia ou clínica não encontrada.');if(g.status!=='draft')throw Error('Somente rascunhos podem ser liberados.');const now=new Date().toISOString();const r=await c.from('mentalita_patient_tiss_guides').update({status:'ready',finalized_at:now,finalized_by:U(),updated_at:now}).eq('id',id).eq('clinic_id',clinic).select('id,status').single();if(r.error)throw r.error;if(r.data.status!=='ready')throw Error('A guia não foi confirmada como pronta.');await render();}
async function createLot(){const c=S(),clinic=C();if(!c||!clinic)throw Error('Clínica não identificada.');const ids=[...document.querySelectorAll('[data-guide-check]:checked')].map(x=>x.value);if(!ids.length)throw Error('Selecione pelo menos uma guia pronta.');const gs=await guides(),chosen=gs.filter(g=>ids.includes(g.id));if(chosen.length!==ids.length||chosen.some(g=>g.status!=='ready'))throw Error('Somente guias prontas podem entrar em lote.');const conv=[...new Set(chosen.map(g=>g.convenio_id||'sem-convenio'))];if(conv.length>1)throw Error('As guias selecionadas pertencem a convênios diferentes.');const total=chosen.reduce((s,g)=>s+Number(g.total_amount||0),0);const lot=await c.from('mentalita_billing_lots').insert({clinic_id:clinic,status:'draft',total_amount:total,guide_count:chosen.length,created_by:U(),notes:null}).select('id').single();if(lot.error)throw lot.error;const links=await c.from('mentalita_billing_lot_guides').insert(chosen.map(g=>({clinic_id:clinic,lot_id:lot.data.id,guide_id:g.id})));if(links.error){await c.from('mentalita_billing_lots').delete().eq('id',lot.data.id).eq('clinic_id',clinic);throw links.error;}const now=new Date().toISOString();const up=await c.from('mentalita_patient_tiss_guides').update({status:'batched',updated_at:now}).in('id',chosen.map(g=>g.id)).eq('clinic_id',clinic);if(up.error)throw up.error;activeTab='lotes';await render();}
async function submitLot(id){const c=S(),clinic=C();const l=(await lots()).find(x=>x.id===id);if(!c||!clinic||!l)throw Error('Lote não encontrado.');if(l.status!=='draft')throw Error('Somente lotes em rascunho podem ser enviados.');const links=await lotLinks([id]);if(!links.length)throw Error('O lote não possui guias vinculadas.');const now=new Date().toISOString();const r=await c.from('mentalita_billing_lots').update({status:'sent',submitted_at:now,updated_at:now}).eq('id',id).eq('clinic_id',clinic).select('id,status').single();if(r.error)throw r.error;const u=await c.from('mentalita_patient_tiss_guides').update({status:'sent',updated_at:now}).in('id',links.map(x=>x.guide_id)).eq('clinic_id',clinic);if(u.error)throw u.error;await render();}
async function saveReceipt(){const c=S(),clinic=C();const amount=Number(document.getElementById('receiptAmount')?.value);if(!c||!clinic)throw Error('Clínica não identificada.');if(!Number.isFinite(amount)||amount<=0)throw Error('Informe um valor recebido maior que zero.');const r=await c.from('mentalita_billing_receipts').insert({clinic_id:clinic,lot_id:document.getElementById('receiptLot')?.value||null,received_at:document.getElementById('receiptDate')?.value,amount,status:'received',reference:document.getElementById('receiptReference')?.value.trim()||null,notes:document.getElementById('receiptNotes')?.value.trim()||null,created_by:U()}).select('id').single();if(r.error)throw r.error;closeModal();await syncLotPayment(r.data.id);await render();}
async function syncLotPayment(receiptId){const c=S(),clinic=C();const r=await c.from('mentalita_billing_receipts').select('lot_id').eq('id',receiptId).single();if(r.error||!r.data?.lot_id)return;const ls=(await lots()).find(x=>x.id===r.data.lot_id);if(!ls)return;const rs=(await rows('mentalita_billing_receipts')).filter(x=>x.lot_id===ls.id&&x.status==='received');const total=rs.reduce((a,x)=>a+Number(x.amount||0),0);const next=total>=Number(ls.total_amount||0)?'paid':ls.status==='draft'?'draft':'processed';await c.from('mentalita_billing_lots').update({status:next,paid_at:next==='paid'?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq('id',ls.id).eq('clinic_id',clinic);}
async function retifyReceipt(id){const rs=await receipts(),r=rs.find(x=>x.id===id);if(!r)throw Error('Recebimento não encontrado.');document.getElementById('billingWorkspace').insertAdjacentHTML('beforeend',retifyModal(r));}
async function saveRetification(){const c=S(),clinic=C(),id=document.getElementById('retifyId')?.value,old=(await receipts()).find(x=>x.id===id);if(!c||!clinic||!old)throw Error('Recebimento não encontrado.');const reason=document.getElementById('retifyReason')?.value.trim();if(!reason)throw Error('Informe o motivo da retificação.');const nv={received_at:document.getElementById('retifyDate').value,amount:Number(document.getElementById('retifyAmount').value),status:old.status,reference:document.getElementById('retifyReference').value.trim()||null,notes:document.getElementById('retifyNotes').value.trim()||null};if(!nv.amount||nv.amount<=0)throw Error('Informe um valor maior que zero.');const rev=await c.from('mentalita_billing_receipt_revisions').insert({clinic_id:clinic,receipt_id:id,original_received_at:old.received_at,original_amount:old.amount,original_status:old.status,original_reference:old.reference,original_notes:old.notes,new_received_at:nv.received_at,new_amount:nv.amount,new_status:nv.status,new_reference:nv.reference,new_notes:nv.notes,reason,corrected_by:U()});if(rev.error)throw rev.error;const up=await c.from('mentalita_billing_receipts').update(nv).eq('id',id).eq('clinic_id',clinic);if(up.error)throw up.error;closeModal();await syncLotPayment(id);await render();}
async function saveDenial(edit=false){const c=S(),clinic=C();if(!c||!clinic)throw Error('Clínica não identificada.');const amount=Number(document.getElementById('denialAmount')?.value);if(!Number.isFinite(amount)||amount<=0)throw Error('Informe um valor de glosa maior que zero.');const guide=document.getElementById('denialGuide')?.value||null,lot=document.getElementById('denialLot')?.value||null,reason=document.getElementById('denialReason')?.value.trim()||null,notes=document.getElementById('denialNotes')?.value.trim()||null;if(!guide&&!lot)throw Error('Vincule a glosa a uma guia ou a um lote.');if(edit){const id=document.getElementById('denialRevisionId').value,old=(await denials()).find(x=>x.id===id),revReason=document.getElementById('denialRevisionReason')?.value.trim();if(!old)throw Error('Glosa não encontrada.');if(!revReason)throw Error('Informe o motivo da retificação.');const rev=await c.from('mentalita_billing_denial_revisions').insert({clinic_id:clinic,denial_id:id,original_amount:old.amount,original_status:old.status,original_reason:old.reason,original_notes:old.notes,new_amount:amount,new_status:old.status,new_reason:reason,new_notes:notes,reason:revReason,corrected_by:U()});if(rev.error)throw rev.error;const up=await c.from('mentalita_billing_denials').update({guide_id:guide,lot_id:lot,amount,reason,notes}).eq('id',id).eq('clinic_id',clinic);if(up.error)throw up.error;}else{const r=await c.from('mentalita_billing_denials').insert({clinic_id:clinic,guide_id:guide,lot_id:lot,amount,reason,status:'open',notes}).select('id').single();if(r.error)throw r.error;}closeModal();await render();}
async function resolveDenial(){const c=S(),clinic=C(),id=document.getElementById('resolveId').value,d=(await denials()).find(x=>x.id===id);if(!c||!clinic||!d)throw Error('Glosa não encontrada.');const recovered=Number(document.getElementById('resolveRecovered').value||0),notes=document.getElementById('resolveNotes').value.trim()||null;if(recovered<0||recovered>Number(d.amount||0))throw Error('O valor recuperado não pode ser maior que a glosa.');const now=new Date().toISOString();const r=await c.from('mentalita_billing_denials').update({status:'resolved',resolved_at:now,resolved_by:U(),recovered_amount:recovered,notes}).eq('id',id).eq('clinic_id',clinic).select('id,status').single();if(r.error)throw r.error;closeModal();await render();}
async function openDenialEdit(id){const d=(await denials()).find(x=>x.id===id);if(!d)throw Error('Glosa não encontrada.');document.getElementById('billingWorkspace').insertAdjacentHTML('beforeend',denialModal(await lots(),await guides(),d));}
async function openDenialResolve(id){const d=(await denials()).find(x=>x.id===id);if(!d)throw Error('Glosa não encontrada.');document.getElementById('billingWorkspace').insertAdjacentHTML('beforeend',resolveModal(d));}
function closeModal(){document.querySelectorAll('[data-billing-modal]').forEach(x=>x.remove());}
function err(e){console.error('[Mentalita Faturamento]',e);alert(e?.message||String(e));}
function bind(){const host=document.getElementById('billingWorkspace');if(!host||host.dataset.billingBound)return;host.dataset.billingBound='1';host.addEventListener('click',async e=>{const tab=e.target.closest('[data-billing-tab]');if(tab){activeTab=tab.dataset.billingTab;await render();return;}const rel=e.target.closest('[data-release-guide]');if(rel){try{await releaseGuide(rel.dataset.releaseGuide);}catch(x){err(x);}return;}const create=e.target.closest('[data-create-lot]');if(create&&!create.disabled){try{await createLot();}catch(x){err(x);}return;}const submit=e.target.closest('[data-submit-lot]');if(submit){try{await submitLot(submit.dataset.submitLot);}catch(x){err(x);}return;}const nr=e.target.closest('[data-new-receipt]');if(nr){document.getElementById('billingWorkspace').insertAdjacentHTML('beforeend',receiptModal(await lots()));return;}const rr=e.target.closest('[data-retify-receipt]');if(rr){try{await retifyReceipt(rr.dataset.retifyReceipt);}catch(x){err(x);}return;}const sr=e.target.closest('[data-save-receipt]');if(sr){try{await saveReceipt();}catch(x){err(x);}return;}const srt=e.target.closest('[data-save-retification]');if(srt){try{await saveRetification();}catch(x){err(x);}return;}const nd=e.target.closest('[data-new-denial]');if(nd){try{document.getElementById('billingWorkspace').insertAdjacentHTML('beforeend',denialModal(await lots(),await guides()));}catch(x){err(x);}return;}const rd=e.target.closest('[data-retify-denial]');if(rd){try{await openDenialEdit(rd.dataset.retifyDenial);}catch(x){err(x);}return;}const res=e.target.closest('[data-resolve-denial]');if(res){try{await openDenialResolve(res.dataset.resolveDenial);}catch(x){err(x);}return;}const sd=e.target.closest('[data-save-denial]');if(sd){try{await saveDenial(sd.dataset.editDenial==='1');}catch(x){err(x);}return;}const srz=e.target.closest('[data-save-resolution]');if(srz){try{await resolveDenial();}catch(x){err(x);}return;}const close=e.target.closest('[data-close-billing-modal]');if(close){closeModal();return;}});}
window.buildFaturamento=function(){return '<div id="billingWorkspace"></div>';};
window.renderFaturamento=function(){bind();return render();};
})();