// Mentalita — ações incrementais do Financeiro
(function(){
  const tables={receitas:'mentalita_financial_revenues',despesas:'mentalita_financial_expenses',receber:'mentalita_financial_receivables',pagar:'mentalita_financial_payables',repasses:'mentalita_financial_repasses'};
  const clinic=()=>window.PLURI_CLINIC?.id||'';
  const client=()=>window.PLURI_SUPABASE;
  const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v||0));
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const dateBR=v=>v?new Date(v+'T00:00:00').toLocaleDateString('pt-BR'):'—';
  const today=()=>new Date().toISOString().slice(0,10);
  const toast=m=>typeof showToast==='function'&&showToast(m);
  async function rows(tab){const order={receitas:'received_at',despesas:'due_at',receber:'due_at',pagar:'due_at',repasses:'period_end'}[tab];const {data,error}=await client().from(tables[tab]).select('*').eq('clinic_id',clinic()).order(order,{ascending:false});if(error){console.error(error);toast('Não foi possível carregar o registro.');return []}return data||[]}
  function modal(id,title,fields){return `<div class="modal-overlay show" id="finActionModal" role="dialog" aria-modal="true"><div class="modal"><div class="modal-header"><h3>${title}</h3><button type="button" class="modal-close" id="finActionClose" aria-label="Fechar">×</button></div><div class="modal-body">${fields}</div><div class="modal-footer"><button type="button" class="btn btn-outline" id="finActionCancel">Cancelar</button><button type="button" class="btn btn-primary" id="finActionSave">Salvar alterações</button></div></div></div>`}
  function field(id,label,value,type='text',extra=''){return `<div class="form-group"><label for="${id}">${label}</label><input id="${id}" type="${type}" value="${esc(value)}" ${extra}></div>`}
  function select(id,label,value,opts){return `<div class="form-group"><label for="${id}">${label}</label><select id="${id}">${opts.map(([v,t])=>`<option value="${esc(v)}" ${String(v)===String(value)?'selected':''}>${t}</option>`).join('')}</select></div>`}
  function formFor(tab,r){
    if(tab==='receitas')return `<div class="form-row">${field('faDesc','Descrição',r.description)}${field('faAmount','Valor',r.amount,'number','min="0.01" step="0.01"')}</div><div class="form-row">${field('faDate','Data',r.received_at,'date')}${select('faStatus','Status',r.status,[['received','Recebido'],['pending','Pendente'],['cancelled','Cancelado']])}</div>`;
    if(tab==='despesas')return `<div class="form-row">${field('faDesc','Descrição',r.description)}${field('faAmount','Valor',r.amount,'number','min="0.01" step="0.01"')}</div><div class="form-row">${field('faDate','Vencimento',r.due_at,'date')}${select('faStatus','Status',r.status,[['pending','Pendente'],['paid','Pago'],['cancelled','Cancelado']])}</div>`;
    if(tab==='receber')return `<div class="form-row">${field('faDesc','Descrição',r.description)}${field('faAmount','Valor',r.amount,'number','min="0.01" step="0.01"')}</div><div class="form-row">${field('faDate','Vencimento',r.due_at,'date')}${select('faSource','Origem',r.source,[['Particular','Particular'],['Convênio','Convênio'],['Outro','Outro']])}</div>${select('faStatus','Status',r.status,[['pending','Pendente'],['received','Recebido'],['cancelled','Cancelado']])}`;
    if(tab==='pagar')return `<div class="form-row">${field('faDesc','Descrição',r.description)}${field('faSupplier','Fornecedor',r.supplier||'')}</div><div class="form-row">${field('faAmount','Valor',r.amount,'number','min="0.01" step="0.01"')}${field('faDate','Vencimento',r.due_at,'date')}</div>${select('faStatus','Status',r.status,[['pending','Pendente'],['paid','Pago'],['cancelled','Cancelado']])}`;
    return `<div class="form-row">${field('faProfessional','Profissional',r.professional_name||'')}${select('faStatus','Status',r.status,[['pending','Pendente'],['paid','Pago'],['cancelled','Cancelado']])}</div><div class="form-row">${field('faStart','Início',r.period_start,'date')}${field('faEnd','Fim',r.period_end,'date')}</div><div class="form-row">${field('faGross','Valor bruto',r.gross_amount,'number','min="0" step="0.01"')}${field('faPercentage','Percentual',r.percentage,'number','min="0" max="100" step="0.01"')}</div>${field('faRepasse','Valor do repasse',r.amount,'number','min="0" step="0.01"')}`;
  }
  function bindRows(tab){const table=document.querySelector('#financeiroContent table');if(!table||!table.tBodies[0])return;const trs=[...table.tBodies[0].rows];trs.forEach((tr,index)=>{if(tr.dataset.finActions)return;tr.dataset.finActions='1';const td=document.createElement('td');td.innerHTML='<button type="button" class="btn btn-outline btn-sm" data-fa-edit>Editar</button> <button type="button" class="btn btn-outline btn-sm" data-fa-delete>Excluir</button>';tr.appendChild(td);td.querySelector('[data-fa-edit]').addEventListener('click',()=>edit(tab,index));td.querySelector('[data-fa-delete]').addEventListener('click',()=>remove(tab,index))});const head=table.tHead?.rows[0];if(head&&!head.querySelector('[data-fa-head]')){const th=document.createElement('th');th.textContent='Ações';th.dataset.faHead='1';head.appendChild(th)}}
  async function remove(tab,index){const rs=await rows(tab);const r=rs[index];if(!r)return toast('Registro não encontrado.');if(!confirm('Excluir este registro?'))return;const {error}=await client().from(tables[tab]).delete().eq('id',r.id).eq('clinic_id',clinic());if(error){console.error(error);return toast('Não foi possível excluir.')}toast('Registro excluído.');await window.renderFinanceiroTab(tab)}
  async function edit(tab,index){const rs=await rows(tab),r=rs[index];if(!r)return toast('Registro não encontrado.');document.body.insertAdjacentHTML('beforeend',modal('finActionModal','Editar '+({receitas:'receita',despesas:'despesa',receber:'conta a receber',pagar:'conta a pagar',repasses:'repasse'}[tab]),formFor(tab,r)));const close=()=>document.getElementById('finActionModal')?.remove();document.getElementById('finActionClose').onclick=close;document.getElementById('finActionCancel').onclick=close;document.getElementById('finActionSave').onclick=async()=>{const data={};if(tab==='receitas')Object.assign(data,{description:document.getElementById('faDesc').value.trim(),amount:Number(document.getElementById('faAmount').value),received_at:document.getElementById('faDate').value,status:document.getElementById('faStatus').value});if(tab==='despesas')Object.assign(data,{description:document.getElementById('faDesc').value.trim(),amount:Number(document.getElementById('faAmount').value),due_at:document.getElementById('faDate').value,status:document.getElementById('faStatus').value});if(tab==='receber')Object.assign(data,{description:document.getElementById('faDesc').value.trim(),amount:Number(document.getElementById('faAmount').value),due_at:document.getElementById('faDate').value,source:document.getElementById('faSource').value,status:document.getElementById('faStatus').value,received_at:document.getElementById('faStatus').value==='received'?document.getElementById('faDate').value:null});if(tab==='pagar')Object.assign(data,{description:document.getElementById('faDesc').value.trim(),supplier:document.getElementById('faSupplier').value.trim()||null,amount:Number(document.getElementById('faAmount').value),due_at:document.getElementById('faDate').value,status:document.getElementById('faStatus').value});if(tab==='repasses')Object.assign(data,{professional_name:document.getElementById('faProfessional').value.trim(),period_start:document.getElementById('faStart').value,period_end:document.getElementById('faEnd').value,gross_amount:Number(document.getElementById('faGross').value),percentage:Number(document.getElementById('faPercentage').value),amount:Number(document.getElementById('faRepasse').value),status:document.getElementById('faStatus').value});if(!data.description&&tab!=='repasses'||(tab==='repasses'&&!data.professional_name)){return toast('Preencha os campos obrigatórios.')}const {error}=await client().from(tables[tab]).update(data).eq('id',r.id).eq('clinic_id',clinic());if(error){console.error(error);return toast('Não foi possível salvar as alterações.')}close();toast('Alterações salvas.');await window.renderFinanceiroTab(tab)} }
  const original=window.renderFinanceiroTab; if(typeof original!=='function')return; window.renderFinanceiroTab=async function(tab){await original(tab);if(['receitas','despesas','receber','pagar','repasses'].includes(tab))bindRows(tab)};
})();
