// Mentalita — filtros e período do Financeiro (incremental)
(function(){
  const tabs=['receitas','despesas','receber','pagar','repasses'];
  const labels={receitas:'Receitas',despesas:'Despesas',receber:'Contas a receber',pagar:'Contas a pagar',repasses:'Repasses'};
  const tableByTab={receitas:'mentalita_financial_revenues',despesas:'mentalita_financial_expenses',receber:'mentalita_financial_receivables',pagar:'mentalita_financial_payables',repasses:'mentalita_financial_repasses'};
  const clinic=()=>window.PLURI_CLINIC?.id||'';const db=()=>window.PLURI_SUPABASE;
  const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v||0));
  const dateBR=v=>v?new Date(v+'T00:00:00').toLocaleDateString('pt-BR'):'—';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const period=()=>{const now=new Date(),y=now.getFullYear(),m=String(now.getMonth()+1).padStart(2,'0');return {from:`${y}-${m}-01`,to:new Date(y,now.getMonth()+1,0).toISOString().slice(0,10)}};
  let current={from:period().from,to:period().to,status:'all',search:''};
  async function get(tab){const order={receitas:'received_at',despesas:'due_at',receber:'due_at',pagar:'due_at',repasses:'period_end'}[tab];const {data,error}=await db().from(tableByTab[tab]).select('*').eq('clinic_id',clinic()).order(order,{ascending:false});if(error){console.error(error);return []}return data||[]}
  function dateOf(tab,r){return r.received_at||r.due_at||r.period_end||r.created_at?.slice(0,10)||''}
  function matches(tab,r){const d=dateOf(tab,r);const okDate=(!current.from||d>=current.from)&&(!current.to||d<=current.to);const okStatus=current.status==='all'||r.status===current.status;const text=[r.description,r.category,r.source,r.supplier,r.professional_name,r.professional].filter(Boolean).join(' ').toLowerCase();return okDate&&okStatus&&(!current.search||text.includes(current.search.toLowerCase()))}
  function controls(tab){const statuses=tab==='receber'?[['all','Todos'],['pending','Pendente'],['received','Recebido'],['cancelled','Cancelado']]:tab==='pagar'||tab==='despesas'||tab==='repasses'?[['all','Todos'],['pending','Pendente'],['paid','Pago'],['cancelled','Cancelado']]:[['all','Todos'],['received','Recebido'],['pending','Pendente'],['cancelled','Cancelado']];return `<div class="finance-filters" style="display:flex;flex-wrap:wrap;gap:10px;margin-bottom:16px;padding:14px 16px;background:var(--card-bg,#fff);border:1px solid var(--border-color,#e4e7ec);border-radius:10px"><div class="form-group" style="margin:0"><label for="finFilterFrom">De</label><input id="finFilterFrom" type="date" value="${current.from}"></div><div class="form-group" style="margin:0"><label for="finFilterTo">Até</label><input id="finFilterTo" type="date" value="${current.to}"></div><div class="form-group" style="margin:0"><label for="finFilterStatus">Status</label><select id="finFilterStatus">${statuses.map(x=>`<option value="${x[0]}" ${x[0]===current.status?'selected':''}>${x[1]}</option>`).join('')}</select></div><div class="form-group" style="margin:0;min-width:210px"><label for="finFilterSearch">Buscar</label><input id="finFilterSearch" type="search" value="${esc(current.search)}" placeholder="Descrição, fornecedor..."></div><div style="display:flex;align-items:end;gap:8px"><button type="button" class="btn btn-outline" id="finFilterClear">Limpar</button><button type="button" class="btn btn-primary" id="finFilterApply">Aplicar</button></div></div>`}
  function table(tab,rows){if(!rows.length)return '<div style="padding:36px;text-align:center;color:var(--text-secondary)">Nenhum registro encontrado para os filtros selecionados.</div>';const h={receitas:['Data','Descrição','Status','Valor'],despesas:['Vencimento','Descrição','Status','Valor'],receber:['Vencimento','Descrição','Origem','Status','Valor'],pagar:['Vencimento','Descrição','Fornecedor','Status','Valor'],repasses:['Período','Profissional','Bruto','Repasse','Status']}[tab];return `<div style="overflow:auto"><table class="data-table"><thead><tr>${h.map(x=>`<th>${x}</th>`).join('')}<th>Ações</th></tr></thead><tbody>${rows.map(r=>{const cells=tab==='receitas'?`<td>${dateBR(r.received_at)}</td><td>${esc(r.description)}</td><td>${esc(r.status)}</td><td><strong>${money(r.amount)}</strong></td>`:tab==='despesas'?`<td>${dateBR(r.due_at)}</td><td>${esc(r.description)}</td><td>${esc(r.status)}</td><td><strong>${money(r.amount)}</strong></td>`:tab==='receber'?`<td>${dateBR(r.due_at)}</td><td>${esc(r.description)}</td><td>${esc(r.source||'—')}</td><td>${esc(r.status)}</td><td><strong>${money(r.amount)}</strong></td>`:tab==='pagar'?`<td>${dateBR(r.due_at)}</td><td>${esc(r.description)}</td><td>${esc(r.supplier||'—')}</td><td>${esc(r.status)}</td><td><strong>${money(r.amount)}</strong></td>`:`<td>${dateBR(r.period_start)} — ${dateBR(r.period_end)}</td><td>${esc(r.professional_name||r.professional||'—')}</td><td>${money(r.gross_amount)}</td><td><strong>${money(r.amount??r.repasse_amount)}</strong></td><td>${esc(r.status)}</td>`;return `<tr>${cells}<td><button type="button" class="btn btn-outline btn-sm" data-filter-row-id="${esc(r.id)}">Abrir</button></td></tr>`}).join('')}</tbody></table></div>`}
  async function render(tab){if(!tabs.includes(tab))return;const host=document.getElementById('financeiroContent');if(!host)return;const rows=(await get(tab)).filter(r=>matches(tab,r));const title=labels[tab];host.innerHTML=`<div class="card"><div class="card-header" style="display:flex;justify-content:space-between;align-items:center;gap:16px"><div><h3>${title}</h3><p style="font-size:13px;color:var(--text-secondary);margin-top:2px">Filtre os registros por período, status ou busca.</p></div></div><div class="card-body">${controls(tab)}${table(tab,rows)}</div></div>`;bind(tab)}
  function bind(tab){document.getElementById('finFilterApply')?.addEventListener('click',()=>{current={from:document.getElementById('finFilterFrom').value,to:document.getElementById('finFilterTo').value,status:document.getElementById('finFilterStatus').value,search:document.getElementById('finFilterSearch').value.trim()};render(tab)});document.getElementById('finFilterClear')?.addEventListener('click',()=>{current={from:'',to:'',status:'all',search:''};render(tab)});document.querySelectorAll('[data-filter-row-id]').forEach(b=>b.addEventListener('click',()=>window.renderFinanceiroTab?.(tab)))}
  function inject(){const tabsEl=document.getElementById('financeiroTabs');if(!tabsEl)return;tabsEl.querySelectorAll('.tab').forEach(b=>{if(b.dataset.filterBound)return;b.dataset.filterBound='1';b.addEventListener('click',()=>{const tab=b.dataset.tab;if(tab!=='overview')render(tab)})})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',inject);else inject();
})();
