// Mentalita — Central de Faturamento funcional
(function(){
 const S=()=>window.PLURI_SUPABASE||null,C=()=>window.PLURI_CLINIC?.id||null,U=()=>window.PLURI_AUTH_SESSION?.user||null;
 const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
 const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v||0));
 const date=v=>v?new Date(String(v).slice(0,10)+'T00:00:00').toLocaleDateString('pt-BR'):'—';
 const status={draft:'Rascunho',ready:'Pronta',billed:'Faturada',sent:'Enviada',processed:'Processada',paid:'Paga',denied:'Glosada'};
 async function guides(){const c=S();if(!c||!C())return[];const q=await c.from('mentalita_patient_tiss_guides').select('*').eq('clinic_id',C()).order('created_at',{ascending:false});return q.data||[];}
 async function lots(){const c=S();if(!c||!C())return[];const q=await c.from('mentalita_billing_lots').select('*').eq('clinic_id',C()).order('created_at',{ascending:false});return q.data||[];}
 async function receipts(){const c=S();if(!c||!C())return[];const q=await c.from('mentalita_billing_receipts').select('*').eq('clinic_id',C()).order('received_at',{ascending:false});return q.data||[];}
 async function denials(){const c=S();if(!c||!C())return[];const q=await c.from('mentalita_billing_denials').select('*').eq('clinic_id',C()).order('created_at',{ascending:false});return q.data||[];}
 async function patientNames(ids){const c=S();if(!c||!ids.length)return{};const q=await c.from('mentalita_patients').select('id,name').in('id',ids);return Object.fromEntries((q.data||[]).map(x=>[x.id,x.name]));}
 function kpi(l,v,n){return `<div class="billing-kpi"><div class="billing-label">${l}</div><div class="billing-value">${money(v)}</div><div class="billing-note">${n}</div></div>`;}
 async function renderTab(tab){const host=document.getElementById('billingWorkspace');if(!host)return;const [gs,ls,rs,ds]=await Promise.all([guides(),lots(),receipts(),denials()]);const names=await patientNames(gs.map(x=>x.patient_id));const ready=gs.filter(x=>x.status==='ready'),sent=gs.filter(x=>['sent','processed'].includes(x.status)),paid=gs.filter(x=>x.status==='paid');const open=gs.filter(x=>['ready','billed'].includes(x.status)).reduce((s,x)=>s+Number(x.total_amount||0),0),sentV=sent.reduce((s,x)=>s+Number(x.total_amount||0),0),received=rs.reduce((s,x)=>s+Number(x.amount||0),0),denied=ds.filter(x=>x.status==='open').reduce((s,x)=>s+Number(x.amount||0),0);document.querySelectorAll('.billing-kpi').forEach((e,i)=>{e.outerHTML=[kpi('Em aberto',open,'Guias prontas / faturadas'),kpi('Enviado',sentV,'Em processamento'),kpi('Recebido',received,'Pagamentos registrados'),kpi('Glosado',denied,'Glosas em aberto')][i];});
 let html='';
 if(tab==='guias'){html=`<div class="patient-info-card"><div class="billing-head"><div><h3>Guias prontas para faturamento</h3><p class="section-subtitle">Selecione as guias e agrupe em um lote.</p></div><button class="btn btn-primary" id="billingCreateLot" ${ready.length?'':'disabled'}>Criar lote</button></div>${ready.length?`<div class="billing-list">${ready.map(g=>`<label class="billing-row"><input type="checkbox" class="billing-guide-check" value="${g.id}"><div><strong>${esc(names[g.patient_id]||'Paciente')}</strong><div class="billing-note">Guia ${esc(g.guide_number||'sem número')} · execução ${date(g.execution_date)}</div></div><strong>${money(g.total_amount)}</strong></label>`).join('')}</div>`:'<div class="billing-empty">Nenhuma guia pronta para faturamento.</div>'}</div>`;}
 else if(tab==='lotes'){html=`<div class="patient-info-card"><div class="billing-head"><div><h3>Lotes</h3><p class="section-subtitle">Agrupe guias por operadora e acompanhe o ciclo de faturamento.</p></div></div>${ls.length?ls.map(l=>`<div class="billing-row"><div><strong>${esc(l.lot_number||'Lote sem número')}</strong><div class="billing-note">${date(l.created_at)} · ${esc(l.status)}</div></div><div style="text-align:right"><strong>${money(l.total_amount)}</strong><div><button class="btn billing-send" data-id="${l.id}" ${l.status==='draft'?'':'disabled'}>Marcar enviado</button></div></div></div>`).join(''):'<div class="billing-empty">Nenhum lote criado.</div>'}</div>`;}
 else if(tab==='glosas'){html=`<div class="patient-info-card"><div class="billing-head"><div><h3>Glosas</h3><p class="section-subtitle">Registre e acompanhe valores recusados pelo convênio.</p></div><button class="btn btn-primary" id="billingNewDenial">+ Registrar glosa</button></div>${ds.length?ds.map(d=>`<div class="billing-row"><div><strong>${money(d.amount)}</strong><div class="billing-note">${esc(d.reason||'Sem motivo')} · ${esc(d.status)}</div></div><button class="btn billing-resolve" data-id="${d.id}" ${d.status==='open'?'':'disabled'}>Resolver</button></div>`).join(''):'<div class="billing-empty">Nenhuma glosa registrada.</div>'}</div>`;}
 else if(tab==='recebimentos'){html=`<div class="patient-info-card"><div class="billing-head"><div><h3>Recebimentos</h3><p class="section-subtitle">Controle os pagamentos recebidos dos convênios.</p></div><button class="btn btn-primary" id="billingNewReceipt">+ Registrar recebimento</button></div>${rs.length?rs.map(r=>`<div class="billing-row"><div><strong>${money(r.amount)}</strong><div class="billing-note">${date(r.received_at)} · ${esc(r.reference||'Sem referência')}</div></div></div>`).join(''):'<div class="billing-empty">Nenhum recebimento registrado.</div>'}</div>`;}
 else {html=`<div class="patient-info-card"><h3>Fluxo de faturamento</h3><div class="billing-flow"><span>Guias prontas <b>${ready.length}</b></span><span>Lotes <b>${ls.length}</b></span><span>Enviadas <b>${sent.length}</b></span><span>Recebidas <b>${paid.length}</b></span><span>Glosas <b>${ds.filter(x=>x.status==='open').length}</b></span></div></div><div class="billing-grid"><div class="patient-info-card"><h3>Guias aguardando faturamento</h3>${ready.slice(0,8).map(g=>`<div class="billing-row"><div><strong>${esc(names[g.patient_id]||'Paciente')}</strong><div class="billing-note">${date(g.execution_date)}</div></div><strong>${money(g.total_amount)}</strong></div>`).join('')||'<div class="billing-empty">Nenhuma guia pronta.</div>'}</div><div class="patient-info-card"><h3>Últimos lotes</h3>${ls.slice(0,5).map(l=>`<div class="billing-row"><div><strong>${esc(l.lot_number||'Lote')}</strong><div class="billing-note">${date(l.created_at)} · ${esc(l.status)}</div></div><strong>${money(l.total_amount)}</strong></div>`).join('')||'<div class="billing-empty">Nenhum lote.</div>'}</div></div>`;}
 host.innerHTML=html;attachTabEvents(tab);}
 async function createLot(){const ids=[...document.querySelectorAll('.billing-guide-check:checked')].map(x=>x.value);if(!ids.length){alert('Selecione pelo menos uma guia.');return;}const c=S(),gs=await guides(),sel=gs.filter(g=>ids.includes(g.id));const total=sel.reduce((s,g)=>s+Number(g.total_amount||0),0);const {data,error}=await c.from('mentalita_billing_lots').insert({clinic_id:C(),lot_number:'L'+Date.now(),status:'draft',total_amount:total,guide_count:sel.length,created_by:U()?.id||null}).select().single();if(error){alert('Não foi possível criar o lote.');console.error(error);return;}await c.from('mentalita_billing_lot_guides').insert(sel.map(g=>({clinic_id:C(),lot_id:data.id,guide_id:g.id})));await c.from('mentalita_patient_tiss_guides').update({status:'billed',updated_at:new Date().toISOString()}).in('id',ids).eq('clinic_id',C());renderTab('lotes');}
 async function sendLot(id){const c=S();const {error}=await c.from('mentalita_billing_lots').update({status:'sent',submitted_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',id).eq('clinic_id',C());if(error){alert('Não foi possível marcar o lote como enviado.');return;}renderTab('lotes');}
 async function newReceipt(){const amount=prompt('Valor recebido (R$):');if(amount===null)return;const value=Number(String(amount).replace(',','.'));if(!Number.isFinite(value)||value<=0){alert('Informe um valor válido.');return;}const ref=prompt('Referência / comprovante (opcional):')||null;const c=S();const {error}=await c.from('mentalita_billing_receipts').insert({clinic_id:C(),received_at:new Date().toISOString().slice(0,10),amount:value,reference:ref,created_by:U()?.id||null});if(error){alert('Não foi possível registrar o recebimento.');return;}renderTab('recebimentos');}
 async function newDenial(){const amount=prompt('Valor da glosa (R$):');if(amount===null)return;const value=Number(String(amount).replace(',','.'));if(!Number.isFinite(value)||value<=0){alert('Informe um valor válido.');return;}const reason=prompt('Motivo da glosa:')||null;const c=S();const {error}=await c.from('mentalita_billing_denials').insert({clinic_id:C(),amount:value,reason,created_at:new Date().toISOString()});if(error){alert('Não foi possível registrar a glosa.');return;}renderTab('glosas');}
 async function resolveDenial(id){const c=S();await c.from('mentalita_billing_denials').update({status:'resolved',resolved_at:new Date().toISOString()}).eq('id',id).eq('clinic_id',C());renderTab('glosas');}
 function attachTabEvents(tab){document.querySelectorAll('.billing-tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.billing-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderTab(b.dataset.billingTab);});document.getElementById('billingCreateLot')?.addEventListener('click',createLot);document.querySelectorAll('.billing-send').forEach(b=>b.onclick=()=>sendLot(b.dataset.id));document.getElementById('billingNewReceipt')?.addEventListener('click',newReceipt);document.getElementById('billingNewDenial')?.addEventListener('click',newDenial);document.querySelectorAll('.billing-resolve').forEach(b=>b.onclick=()=>resolveDenial(b.dataset.id));}
 window.buildFaturamento=()=>{setTimeout(()=>renderTab('visao'),0);return `<div class="billing-page"><div class="billing-top"><div><h2>Faturamento</h2><p class="section-subtitle">Guias TISS, lotes, glosas e recebimentos.</p></div></div><div class="billing-kpis">${kpi('Em aberto',0,'Carregando')} ${kpi('Enviado',0,'Carregando')} ${kpi('Recebido',0,'Carregando')} ${kpi('Glosado',0,'Carregando')}</div><div class="billing-tabs"><button class="btn btn-primary billing-tab active" data-billing-tab="visao">Visão geral</button><button class="btn billing-tab" data-billing-tab="guias">Guias prontas</button><button class="btn billing-tab" data-billing-tab="lotes">Lotes</button><button class="btn billing-tab" data-billing-tab="glosas">Glosas</button><button class="btn billing-tab" data-billing-tab="recebimentos">Recebimentos</button></div><div id="billingWorkspace"></div><style>.billing-page{max-width:1200px}.billing-top{margin-bottom:18px}.billing-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:18px}.billing-kpi{padding:16px;border:1px solid var(--border);border-radius:14px;background:var(--surface,#fff)}.billing-label{font-size:10px;text-transform:uppercase;letter-spacing:.08em;color:var(--text-secondary);font-weight:800}.billing-value{font-size:21px;font-weight:800;margin-top:6px}.billing-note{font-size:11px;color:var(--text-secondary);margin-top:4px}.billing-tabs{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:16px}.billing-head{display:flex;justify-content:space-between;gap:12px;align-items:center;flex-wrap:wrap}.billing-row{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:13px 0;border-bottom:1px solid var(--border)}.billing-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:16px}.billing-flow{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin-top:14px}.billing-flow span{padding:14px;border:1px solid var(--border);border-radius:12px}.billing-flow b{display:block;font-size:20px;margin-top:5px}.billing-empty{padding:24px 4px;color:var(--text-secondary);font-size:13px}.billing-guide-check{margin-right:12px}@media(max-width:800px){.billing-kpis{grid-template-columns:1fr 1fr}.billing-grid{grid-template-columns:1fr}.billing-flow{grid-template-columns:1fr 1fr}}@media(max-width:520px){.billing-kpis{grid-template-columns:1fr}.billing-flow{grid-template-columns:1fr}}</style></div>`;};
})();