// Mentalita — Financeiro: Receitas
(function(){
  const money = v => new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v||0));
  const esc = v => String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const client = () => window.PLURI_SUPABASE;
  const clinicId = () => window.PLURI_CLINIC?.id || '';
  async function getRevenues(){
    const {data,error}=await client().from('mentalita_financial_revenues').select('*').eq('clinic_id',clinicId()).order('received_at',{ascending:false}).order('created_at',{ascending:false});
    if(error){console.error('[Mentalita Financeiro] receitas:',error);return []} return data||[];
  }
  function revenueForm(){return `<div class="modal-overlay" id="financeRevenueModal"><div class="modal"><div class="modal-header"><h3>Nova receita</h3><button class="modal-close" type="button" id="financeRevenueClose">×</button></div><div class="modal-body"><div class="form-row"><div class="form-group"><label>Descrição</label><input id="revenueDescription" type="text" placeholder="Ex.: Atendimento particular"></div><div class="form-group"><label>Categoria</label><select id="revenueCategory"><option>Atendimentos</option><option>Convênios</option><option>Particular</option><option>Outras</option></select></div></div><div class="form-row"><div class="form-group"><label>Valor</label><input id="revenueAmount" type="number" min="0.01" step="0.01" placeholder="0,00"></div><div class="form-group"><label>Data de recebimento</label><input id="revenueDate" type="date" value="${new Date().toISOString().slice(0,10)}"></div></div><div class="form-row"><div class="form-group"><label>Forma de recebimento</label><select id="revenueMethod"><option value="Pix">Pix</option><option value="Transferência">Transferência</option><option value="Cartão">Cartão</option><option value="Dinheiro">Dinheiro</option><option value="Outro">Outro</option></select></div><div class="form-group"><label>Status</label><select id="revenueStatus"><option value="received">Recebido</option><option value="pending">Pendente</option><option value="cancelled">Cancelado</option></select></div></div><div class="form-group"><label>Observações</label><textarea id="revenueNotes" rows="3"></textarea></div></div><div class="modal-footer"><button class="btn btn-outline" type="button" id="financeRevenueCancel">Cancelar</button><button class="btn btn-primary" type="button" id="financeRevenueSave">Salvar receita</button></div></div></div>`}
  async function saveRevenue(){
    const description=document.getElementById('revenueDescription')?.value.trim();
    const amount=Number(document.getElementById('revenueAmount')?.value||0);
    if(!description){showToast('Informe a descrição da receita.');return}
    if(!(amount>0)){showToast('Informe um valor maior que zero.');return}
    const payload={clinic_id:clinicId(),description,category:document.getElementById('revenueCategory').value,amount,received_at:document.getElementById('revenueDate').value,payment_method:document.getElementById('revenueMethod').value,status:document.getElementById('revenueStatus').value,notes:document.getElementById('revenueNotes').value.trim()||null};
    const {error}=await client().from('mentalita_financial_revenues').insert(payload);
    if(error){console.error('[Mentalita Financeiro] salvar receita:',error);showToast('Não foi possível salvar a receita.');return}
    document.getElementById('financeRevenueModal')?.remove();showToast('Receita registrada.');renderFinanceiroTab('receitas');
  }
  function attachRevenue(){
    document.getElementById('financeRevenueOpen')?.addEventListener('click',()=>{document.body.insertAdjacentHTML('beforeend',revenueForm());document.getElementById('financeRevenueClose').onclick=()=>document.getElementById('financeRevenueModal').remove();document.getElementById('financeRevenueCancel').onclick=()=>document.getElementById('financeRevenueModal').remove();document.getElementById('financeRevenueSave').onclick=saveRevenue;});
  }
  window.buildFinanceiro=function(){return `<section class="page-section"><div class="section-header"><div><h2>Financeiro</h2><p>Gestão financeira da clínica.</p></div></div><div class="tabs" id="financeiroTabs"><button class="tab active" data-tab="overview">Visão geral</button><button class="tab" data-tab="receitas">Receitas</button><button class="tab" data-tab="despesas">Despesas</button><button class="tab" data-tab="receber">Contas a receber</button><button class="tab" data-tab="pagar">Contas a pagar</button><button class="tab" data-tab="repasses">Repasses</button></div><div id="financeiroContent"></div></section>`};
  window.renderFinanceiroTab=async function(tab){const c=getEl('financeiroContent');if(!c)return;if(tab!=='receitas'){const titles={overview:['Visão geral','Acompanhe os principais números financeiros da clínica.'],despesas:['Despesas','Lançamentos de saída da clínica.'],receber:['Contas a receber','Valores previstos e pendentes de recebimento.'],pagar:['Contas a pagar','Valores previstos e pendentes de pagamento.'],repasses:['Repasses','Controle de repasses a profissionais e convênios.']};if(tab==='overview'){const revenues=await getRevenues();const received=revenues.filter(x=>x.status==='received').reduce((s,x)=>s+Number(x.amount),0);const pending=revenues.filter(x=>x.status==='pending').reduce((s,x)=>s+Number(x.amount),0);c.innerHTML=`<div class="kpi-row"><div class="kpi-card"><div class="kpi-label">Receitas</div><div class="kpi-value">${money(received)}</div><div class="kpi-sub">${revenues.filter(x=>x.status==='received').length} recebimentos</div></div><div class="kpi-card"><div class="kpi-label">Despesas</div><div class="kpi-value">R$ 0,00</div><div class="kpi-sub">Nenhum lançamento</div></div><div class="kpi-card"><div class="kpi-label">A receber</div><div class="kpi-value">${money(pending)}</div><div class="kpi-sub">${revenues.filter(x=>x.status==='pending').length} pendências</div></div><div class="kpi-card"><div class="kpi-label">A pagar</div><div class="kpi-value">R$ 0,00</div><div class="kpi-sub">Nenhuma pendência</div></div><div class="kpi-card"><div class="kpi-label">Saldo</div><div class="kpi-value">${money(received)}</div><div class="kpi-sub">Receitas menos despesas registradas</div></div></div>`;return}const x=titles[tab]||titles.despesas;c.innerHTML=`<div class="card"><div class="card-header"><div><h3>${x[0]}</h3><p style="font-size:13px;color:var(--text-secondary);margin-top:2px">${x[1]}</p></div></div><div class="card-body" style="padding:32px;text-align:center;color:var(--text-secondary)">Esta área será conectada nas próximas etapas.</div></div>`;return}
    const revenues=await getRevenues();c.innerHTML=`<div class="card"><div class="card-header" style="display:flex;justify-content:space-between;align-items:center;gap:16px"><div><h3>Receitas</h3><p style="font-size:13px;color:var(--text-secondary);margin-top:2px">Registre e acompanhe as entradas financeiras da clínica.</p></div><button class="btn btn-primary" id="financeRevenueOpen">+ Nova receita</button></div><div class="card-body" style="padding:0">${revenues.length?`<div style="overflow:auto"><table class="data-table"><thead><tr><th>Data</th><th>Descrição</th><th>Categoria</th><th>Forma</th><th>Status</th><th>Valor</th></tr></thead><tbody>${revenues.map(r=>`<tr><td>${esc(new Date(r.received_at+'T00:00:00').toLocaleDateString('pt-BR'))}</td><td>${esc(r.description)}</td><td>${esc(r.category)}</td><td>${esc(r.payment_method||'—')}</td><td>${r.status==='received'?'Recebido':r.status==='pending'?'Pendente':'Cancelado'}</td><td><strong>${money(r.amount)}</strong></td></tr>`).join('')}</tbody></table></div>`:`<div style="padding:36px;text-align:center;color:var(--text-secondary)">Nenhuma receita registrada.</div>`}</div></div>`;attachRevenue();};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{if(window.state?.currentPage==='financeiro'){renderPage()}});else if(window.state?.currentPage==='financeiro')renderPage();
})();