// Mentalita — Financeiro
(function(){
  const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v||0));
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const client=()=>window.PLURI_SUPABASE;
  const clinicId=()=>window.PLURI_CLINIC?.id||'';
  const today=()=>new Date().toISOString().slice(0,10);
  const dateBR=v=>v?new Date(v+'T00:00:00').toLocaleDateString('pt-BR'):'—';
  async function query(table,order='created_at'){const {data,error}=await client().from(table).select('*').eq('clinic_id',clinicId()).order(order,{ascending:false});if(error){console.error('[Mentalita Financeiro]',table,error);showToast('Não foi possível carregar os dados.');return []}return data||[]}
  async function getRevenues(){return query('mentalita_financial_revenues','received_at')}
  async function getExpenses(){return query('mentalita_financial_expenses','due_at')}
  async function getReceivables(){return query('mentalita_financial_receivables','due_at')}
  async function getPayables(){return query('mentalita_financial_payables','due_at')}
  function formShell(id,title,body,saveLabel){return `<div class="modal-overlay" id="${id}" role="dialog" aria-modal="true" aria-labelledby="${id}Title"><div class="modal"><div class="modal-header"><h3 id="${id}Title">${title}</h3><button class="modal-close" type="button" data-close="${id}" aria-label="Fechar">×</button></div><div class="modal-body">${body}</div><div class="modal-footer"><button class="btn btn-outline" type="button" data-close="${id}">Cancelar</button><button class="btn btn-primary" type="button" id="${id}Save">${saveLabel}</button></div></div></div>`}
  function revenueForm(){return formShell('financeRevenueModal','Nova receita',`<div class="form-row"><div class="form-group"><label for="revenueDescription">Descrição</label><input id="revenueDescription" type="text" placeholder="Ex.: Atendimento particular"></div><div class="form-group"><label for="revenueCategory">Categoria</label><select id="revenueCategory"><option>Atendimentos</option><option>Convênios</option><option>Particular</option><option>Outras</option></select></div></div><div class="form-row"><div class="form-group"><label for="revenueAmount">Valor</label><input id="revenueAmount" type="number" min="0.01" step="0.01" placeholder="0,00"></div><div class="form-group"><label for="revenueDate">Data</label><input id="revenueDate" type="date" value="${today()}"></div></div><div class="form-row"><div class="form-group"><label for="revenueMethod">Forma de recebimento</label><select id="revenueMethod"><option>Pix</option><option>Transferência</option><option>Cartão</option><option>Dinheiro</option><option>Outro</option></select></div><div class="form-group"><label for="revenueStatus">Status</label><select id="revenueStatus"><option value="received">Recebido</option><option value="pending">Pendente</option><option value="cancelled">Cancelado</option></select></div></div><div class="form-group"><label for="revenueNotes">Observações</label><textarea id="revenueNotes" rows="3"></textarea></div>`,'Salvar receita')}
  function expenseForm(){return formShell('financeExpenseModal','Nova despesa',`<div class="form-row"><div class="form-group"><label for="expenseDescription">Descrição</label><input id="expenseDescription" type="text" placeholder="Ex.: Material de escritório"></div><div class="form-group"><label for="expenseCategory">Categoria</label><select id="expenseCategory"><option>Operacional</option><option>Pessoal</option><option>Materiais</option><option>Impostos</option><option>Aluguel</option><option>Outras</option></select></div></div><div class="form-row"><div class="form-group"><label for="expenseAmount">Valor</label><input id="expenseAmount" type="number" min="0.01" step="0.01" placeholder="0,00"></div><div class="form-group"><label for="expenseDue">Vencimento</label><input id="expenseDue" type="date" value="${today()}"></div></div><div class="form-row"><div class="form-group"><label for="expenseMethod">Forma de pagamento</label><select id="expenseMethod"><option>Pix</option><option>Transferência</option><option>Cartão</option><option>Boleto</option><option>Dinheiro</option><option>Outro</option></select></div><div class="form-group"><label for="expenseStatus">Status</label><select id="expenseStatus"><option value="pending">Pendente</option><option value="paid">Pago</option><option value="cancelled">Cancelado</option></select></div></div><div class="form-group"><label for="expenseNotes">Observações</label><textarea id="expenseNotes" rows="3"></textarea></div>`,'Salvar despesa')}
  function receivableForm(){return formShell('financeReceivableModal','Nova conta a receber',`<div class="form-row"><div class="form-group"><label for="receivableDescription">Descrição</label><input id="receivableDescription" type="text" placeholder="Ex.: Consulta particular"></div><div class="form-group"><label for="receivableSource">Origem</label><select id="receivableSource"><option>Particular</option><option>Convênio</option><option>Outro</option></select></div></div><div class="form-row"><div class="form-group"><label for="receivableAmount">Valor</label><input id="receivableAmount" type="number" min="0.01" step="0.01" placeholder="0,00"></div><div class="form-group"><label for="receivableDue">Vencimento</label><input id="receivableDue" type="date" value="${today()}"></div></div><div class="form-group"><label for="receivableStatus">Status</label><select id="receivableStatus"><option value="pending">Pendente</option><option value="received">Recebido</option><option value="cancelled">Cancelado</option></select></div><div class="form-group"><label for="receivableNotes">Observações</label><textarea id="receivableNotes" rows="3"></textarea></div>`,'Salvar conta')}
  function payableForm(){return formShell('financePayableModal','Nova conta a pagar',`<div class="form-row"><div class="form-group"><label for="payableDescription">Descrição</label><input id="payableDescription" type="text" placeholder="Ex.: Aluguel da clínica"></div><div class="form-group"><label for="payableSupplier">Fornecedor</label><input id="payableSupplier" type="text" placeholder="Nome do fornecedor"></div></div><div class="form-row"><div class="form-group"><label for="payableAmount">Valor</label><input id="payableAmount" type="number" min="0.01" step="0.01" placeholder="0,00"></div><div class="form-group"><label for="payableDue">Vencimento</label><input id="payableDue" type="date" value="${today()}"></div></div><div class="form-group"><label for="payableStatus">Status</label><select id="payableStatus"><option value="pending">Pendente</option><option value="paid">Pago</option><option value="cancelled">Cancelado</option></select></div><div class="form-group"><label for="payableNotes">Observações</label><textarea id="payableNotes" rows="3"></textarea></div>`,'Salvar conta')}
  function closeModal(id){document.getElementById(id)?.remove();document.body.classList.remove('modal-open')}
  function closeModals(){['financeRevenueModal','financeExpenseModal','financeReceivableModal','financePayableModal'].forEach(closeModal)}
  function attachClose(){document.querySelectorAll('#financeRevenueModal [data-close],#financeExpenseModal [data-close],#financeReceivableModal [data-close],#financePayableModal [data-close]').forEach(b=>b.addEventListener('click',()=>closeModal(b.dataset.close)))}
  function showModal(id){const modal=document.getElementById(id);if(!modal)return;modal.classList.add('show');document.body.classList.add('modal-open');requestAnimationFrame(()=>modal.querySelector('input,select,textarea')?.focus())}
  async function saveRevenue(){const description=document.getElementById('revenueDescription')?.value.trim();const amount=Number(document.getElementById('revenueAmount')?.value||0);if(!description){showToast('Informe a descrição da receita.');return}if(!(amount>0)){showToast('Informe um valor maior que zero.');return}const {error}=await client().from('mentalita_financial_revenues').insert({clinic_id:clinicId(),description,category:document.getElementById('revenueCategory').value,amount,received_at:document.getElementById('revenueDate').value,payment_method:document.getElementById('revenueMethod').value,status:document.getElementById('revenueStatus').value,notes:document.getElementById('revenueNotes').value.trim()||null});if(error){console.error(error);showToast('Não foi possível salvar a receita.');return}closeModal('financeRevenueModal');showToast('Receita registrada.');await renderFinanceiroTab('receitas')}
  async function saveExpense(){const description=document.getElementById('expenseDescription')?.value.trim();const amount=Number(document.getElementById('expenseAmount')?.value||0);if(!description){showToast('Informe a descrição da despesa.');return}if(!(amount>0)){showToast('Informe um valor maior que zero.');return}const {error}=await client().from('mentalita_financial_expenses').insert({clinic_id:clinicId(),description,category:document.getElementById('expenseCategory').value,amount,due_at:document.getElementById('expenseDue').value,payment_method:document.getElementById('expenseMethod').value,status:document.getElementById('expenseStatus').value,paid_at:document.getElementById('expenseStatus').value==='paid'?document.getElementById('expenseDue').value:null,notes:document.getElementById('expenseNotes').value.trim()||null});if(error){console.error(error);showToast('Não foi possível salvar a despesa.');return}closeModal('financeExpenseModal');showToast('Despesa registrada.');await renderFinanceiroTab('despesas')}
  async function saveReceivable(){const description=document.getElementById('receivableDescription')?.value.trim();const amount=Number(document.getElementById('receivableAmount')?.value||0);if(!description){showToast('Informe a descrição da conta.');return}if(!(amount>0)){showToast('Informe um valor maior que zero.');return}const status=document.getElementById('receivableStatus').value;const {error}=await client().from('mentalita_financial_receivables').insert({clinic_id:clinicId(),description,source:document.getElementById('receivableSource').value,amount,due_at:document.getElementById('receivableDue').value,received_at:status==='received'?document.getElementById('receivableDue').value:null,status,notes:document.getElementById('receivableNotes').value.trim()||null});if(error){console.error(error);showToast('Não foi possível salvar a conta.');return}closeModal('financeReceivableModal');showToast('Conta a receber registrada.');await renderFinanceiroTab('receber')}
  async function savePayable(){const description=document.getElementById('payableDescription')?.value.trim();const amount=Number(document.getElementById('payableAmount')?.value||0);if(!description){showToast('Informe a descrição da conta.');return}if(!(amount>0)){showToast('Informe um valor maior que zero.');return}const status=document.getElementById('payableStatus').value;const {error}=await client().from('mentalita_financial_payables').insert({clinic_id:clinicId(),description,supplier:document.getElementById('payableSupplier').value.trim()||null,amount,due_at:document.getElementById('payableDue').value,status,paid_at:status==='paid'?document.getElementById('payableDue').value:null,notes:document.getElementById('payableNotes').value.trim()||null});if(error){console.error(error);showToast('Não foi possível salvar a conta.');return}closeModal('financePayableModal');showToast('Conta a pagar registrada.');await renderFinanceiroTab('pagar')}
  function openRevenue(){closeModals();document.body.insertAdjacentHTML('beforeend',revenueForm());attachClose();document.getElementById('financeRevenueModalSave')?.addEventListener('click',saveRevenue);showModal('financeRevenueModal')}
  function openExpense(){closeModals();document.body.insertAdjacentHTML('beforeend',expenseForm());attachClose();document.getElementById('financeExpenseModalSave')?.addEventListener('click',saveExpense);showModal('financeExpenseModal')}
  function openReceivable(){closeModals();document.body.insertAdjacentHTML('beforeend',receivableForm());attachClose();document.getElementById('financeReceivableModalSave')?.addEventListener('click',saveReceivable);showModal('financeReceivableModal')}
  function openPayable(){closeModals();document.body.insertAdjacentHTML('beforeend',payableForm());attachClose();document.getElementById('financePayableModalSave')?.addEventListener('click',savePayable);showModal('financePayableModal')}
  function tableCard(title,subtitle,button,body){return `<div class="card"><div class="card-header" style="display:flex;justify-content:space-between;align-items:center;gap:16px"><div><h3>${title}</h3><p style="font-size:13px;color:var(--text-secondary);margin-top:2px">${subtitle}</p></div>${button||''}</div><div class="card-body" style="padding:0">${body}</div></div>`}
  function emptyTable(columns,message){return `<div style="overflow:auto"><table class="data-table"><thead><tr>${columns.map(x=>`<th>${x}</th>`).join('')}</tr></thead></table></div><div style="padding:36px;text-align:center;color:var(--text-secondary)">${message}</div>`}
  window.buildFinanceiro=function(){return `<section class="page-section"><div class="tabs" id="financeiroTabs"><button class="tab active" data-tab="overview">Visão geral</button><button class="tab" data-tab="receitas">Receitas</button><button class="tab" data-tab="despesas">Despesas</button><button class="tab" data-tab="receber">Contas a receber</button><button class="tab" data-tab="pagar">Contas a pagar</button><button class="tab" data-tab="repasses">Repasses</button></div><div id="financeiroContent"></div></section>`}
  window.renderFinanceiroTab=async function(tab){const c=getEl('financeiroContent');if(!c)return;if(tab==='overview'){const [r,e,rr,p]=await Promise.all([getRevenues(),getExpenses(),getReceivables(),getPayables()]);const rec=r.filter(x=>x.status==='received').reduce((s,x)=>s+Number(x.amount),0);const pendRec=rr.filter(x=>x.status==='pending').reduce((s,x)=>s+Number(x.amount),0);const pag=e.filter(x=>x.status==='paid').reduce((s,x)=>s+Number(x.amount),0);const pendPag=p.filter(x=>x.status==='pending').reduce((s,x)=>s+Number(x.amount),0);c.innerHTML=`<div class="kpi-row"><div class="kpi-card"><div class="kpi-label">Receitas</div><div class="kpi-value">${money(rec)}</div><div class="kpi-sub">${r.filter(x=>x.status==='received').length} recebimentos</div></div><div class="kpi-card"><div class="kpi-label">Despesas</div><div class="kpi-value">${money(pag)}</div><div class="kpi-sub">${e.filter(x=>x.status==='paid').length} pagamentos</div></div><div class="kpi-card"><div class="kpi-label">A receber</div><div class="kpi-value">${money(pendRec)}</div><div class="kpi-sub">${rr.filter(x=>x.status==='pending').length} pendências</div></div><div class="kpi-card"><div class="kpi-label">A pagar</div><div class="kpi-value">${money(pendPag)}</div><div class="kpi-sub">${p.filter(x=>x.status==='pending').length} pendências</div></div><div class="kpi-card"><div class="kpi-label">Saldo</div><div class="kpi-value">${money(rec-pag)}</div><div class="kpi-sub">Receitas menos despesas pagas</div></div></div>`;return}
    if(tab==='receitas'){const rows=await getRevenues();const body=rows.length?`<div style="overflow:auto"><table class="data-table"><thead><tr><th>Data</th><th>Descrição</th><th>Categoria</th><th>Forma</th><th>Status</th><th>Valor</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${dateBR(r.received_at)}</td><td>${esc(r.description)}</td><td>${esc(r.category)}</td><td>${esc(r.payment_method||'—')}</td><td>${r.status==='received'?'Recebido':r.status==='pending'?'Pendente':'Cancelado'}</td><td><strong>${money(r.amount)}</strong></td></tr>`).join('')}</tbody></table></div>`:'<div style="padding:36px;text-align:center;color:var(--text-secondary)">Nenhuma receita registrada.</div>';c.innerHTML=tableCard('Receitas','Registre e acompanhe as entradas financeiras da clínica.','<button class="btn btn-primary" id="financeRevenueOpen">+ Nova receita</button>',body);document.getElementById('financeRevenueOpen')?.addEventListener('click',openRevenue);return}
    if(tab==='despesas'){const rows=await getExpenses();const body=rows.length?`<div style="overflow:auto"><table class="data-table"><thead><tr><th>Vencimento</th><th>Descrição</th><th>Categoria</th><th>Forma</th><th>Status</th><th>Valor</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${dateBR(r.due_at)}</td><td>${esc(r.description)}</td><td>${esc(r.category)}</td><td>${esc(r.payment_method||'—')}</td><td>${r.status==='paid'?'Pago':r.status==='pending'?'Pendente':'Cancelado'}</td><td><strong>${money(r.amount)}</strong></td></tr>`).join('')}</tbody></table></div>`:'<div style="padding:36px;text-align:center;color:var(--text-secondary)">Nenhuma despesa registrada.</div>';c.innerHTML=tableCard('Despesas','Registre e acompanhe as saídas financeiras da clínica.','<button class="btn btn-primary" id="financeExpenseOpen">+ Nova despesa</button>',body);document.getElementById('financeExpenseOpen')?.addEventListener('click',openExpense);return}
    if(tab==='receber'){const rows=await getReceivables();const body=rows.length?`<div style="overflow:auto"><table class="data-table"><thead><tr><th>Vencimento</th><th>Descrição</th><th>Origem</th><th>Status</th><th>Valor</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${dateBR(r.due_at)}</td><td>${esc(r.description)}</td><td>${esc(r.source||'—')}</td><td>${r.status==='received'?'Recebido':r.status==='pending'?'Pendente':'Cancelado'}</td><td><strong>${money(r.amount)}</strong></td></tr>`).join('')}</tbody></table></div>`:'<div style="padding:36px;text-align:center;color:var(--text-secondary)">Nenhuma conta a receber registrada.</div>';c.innerHTML=tableCard('Contas a receber','Acompanhe valores previstos, vencimentos e recebimentos.','<button class="btn btn-primary" id="financeReceivableOpen">+ Nova conta a receber</button>',body);document.getElementById('financeReceivableOpen')?.addEventListener('click',openReceivable);return}
    if(tab==='pagar'){const rows=await getPayables();const body=rows.length?`<div style="overflow:auto"><table class="data-table"><thead><tr><th>Vencimento</th><th>Descrição</th><th>Fornecedor</th><th>Status</th><th>Valor</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${dateBR(r.due_at)}</td><td>${esc(r.description)}</td><td>${esc(r.supplier||'—')}</td><td>${r.status==='paid'?'Pago':r.status==='pending'?'Pendente':'Cancelado'}</td><td><strong>${money(r.amount)}</strong></td></tr>`).join('')}</tbody></table></div>`:'<div style="padding:36px;text-align:center;color:var(--text-secondary)">Nenhuma conta a pagar registrada.</div>';c.innerHTML=tableCard('Contas a pagar','Acompanhe fornecedores, vencimentos e pagamentos.','<button class="btn btn-primary" id="financePayableOpen">+ Nova conta a pagar</button>',body);document.getElementById('financePayableOpen')?.addEventListener('click',openPayable);return}
    c.innerHTML=tableCard('Repasses','Controle dos repasses a profissionais e demais parceiros.','',emptyTable(['Período','Profissional','Bruto','Repasse','Status'],'Nenhum repasse registrado.'));
  }
  function renderCurrentFinanceiro(){const c=getEl('financeiroContent');if(!c||!window.state||state.currentPage!=='financeiro'||c.dataset.rendered==='1')return;c.dataset.rendered='1';renderFinanceiroTab('overview')}
  const pageObserver=new MutationObserver(renderCurrentFinanceiro);
  function startObserver(){const p=getEl('pageContainer');if(p)pageObserver.observe(p,{childList:true,subtree:true});renderCurrentFinanceiro()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',startObserver);else startObserver();
})();
