// Mentalita — Anexos clínicos do prontuário
(function installMentalitaProntuarioAnexos(){
  if(window.__mentalitaProntuarioAnexos)return;
  const client=()=>window.PLURI_SUPABASE||null;
  const patient=()=>window.state?.selectedPatient||(typeof state!=='undefined'?state.selectedPatient:null);
  const clinic=()=>window.PLURI_CLINIC?.id||null;
  const user=()=>window.PLURI_AUTH_SESSION?.user||null;
  const pid=p=>p?.id||p?.ID||p?._id||null;
  const esc=v=>typeof patientEscape==='function'?patientEscape(v):String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;');
  const notify=m=>typeof showToast==='function'?showToast(m):console.log('[Mentalita]',m);
  const MAX=10*1024*1024,allowed=['application/pdf','image/jpeg','image/png'];
  const pending={files:[],startedAt:null,busy:false};
  async function audit(recordId,action,metadata={}){const c=client(),p=patient(),u=user();if(!c||!clinic()||!pid(p)||!recordId)return;const {error}=await c.from('mentalita_patient_record_audit').insert({clinic_id:clinic(),patient_id:pid(p),record_id:recordId,actor_user_id:u?.id||null,action,occurred_at:new Date().toISOString(),metadata:{...metadata,source:'mentalita-web'}});if(error)console.warn('[Mentalita] auditoria do anexo:',error.message);}
  async function fileHash(file){const b=await file.arrayBuffer(),d=await crypto.subtle.digest('SHA-256',b);return Array.from(new Uint8Array(d)).map(x=>x.toString(16).padStart(2,'0')).join('');}
  function humanSize(n){if(!n)return'0 KB';if(n<1024*1024)return`${Math.round(n/1024)} KB`;return`${(n/1024/1024).toFixed(1)} MB`;}
  function safeName(n){return n.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9._-]+/g,'_').slice(0,140);}
  function injectDraft(){
    const form=document.getElementById('mpForm');if(!form||document.getElementById('mpAttachmentsDraft'))return;
    const wrap=document.createElement('div');wrap.id='mpAttachmentsDraft';wrap.style.cssText='margin:2px 0 16px';
    wrap.innerHTML=`<div style="font-size:12px;font-weight:700;margin-bottom:7px">Anexos clínicos <span style="font-weight:500;color:var(--text-secondary)">(opcional)</span></div><label for="mpAttachmentInput" style="display:flex;align-items:center;justify-content:center;min-height:74px;border:1.5px dashed var(--border);border-radius:12px;background:var(--hover-bg);cursor:pointer;padding:12px;text-align:center"><div><div style="font-size:13px;font-weight:750">📎 Adicionar exames ou documentos</div><div style="font-size:10.5px;color:var(--text-secondary);margin-top:4px">PDF, JPG ou PNG · até 10 MB por arquivo</div></div></label><input id="mpAttachmentInput" type="file" accept="application/pdf,image/jpeg,image/png" multiple hidden><div id="mpAttachmentList" style="margin-top:7px"></div>`;
    const actions=form.querySelector('button[type="submit"]')?.parentElement;form.insertBefore(wrap,actions||null);
    wrap.querySelector('#mpAttachmentInput').addEventListener('change',e=>{for(const f of Array.from(e.target.files||[])){if(!allowed.includes(f.type)){notify('Formato não permitido: '+f.name);continue;}if(f.size>MAX){notify('Arquivo acima de 10 MB: '+f.name);continue;}if(!pending.files.some(x=>x.name===f.name&&x.size===f.size))pending.files.push(f);}e.target.value='';renderDraft();});
    renderDraft();
  }
  function renderDraft(){const box=document.getElementById('mpAttachmentList');if(!box)return;box.innerHTML=pending.files.map((f,i)=>`<div style="display:flex;align-items:center;justify-content:space-between;gap:8px;padding:7px 9px;border:1px solid var(--border);border-radius:9px;margin-top:5px;background:var(--surface,#fff)"><div style="min-width:0"><div style="font-size:11px;font-weight:700;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">${esc(f.name)}</div><div style="font-size:10px;color:var(--text-secondary)">${humanSize(f.size)}</div></div><button type="button" class="btn mpRemoveDraft" data-i="${i}" style="padding:4px 7px">Remover</button></div>`).join('');box.querySelectorAll('.mpRemoveDraft').forEach(b=>b.onclick=()=>{pending.files.splice(Number(b.dataset.i),1);renderDraft();});}
  async function findNewRecord(){const c=client(),p=patient(),cl=clinic(),id=pid(p);if(!c||!cl||!id||!pending.startedAt)return null;const start=new Date(pending.startedAt).getTime();const {data,error}=await c.from('mentalita_patient_records').select('id,created_at').eq('clinic_id',cl).eq('patient_id',id).order('created_at',{ascending:false}).limit(5);if(error)return null;return(data||[]).find(r=>new Date(r.created_at).getTime()>=start-3000)||null;}
  async function uploadForRecord(record){const c=client(),p=patient(),u=user(),cl=clinic(),id=pid(p);if(!c||!p||!cl||!id||!record||!pending.files.length)return;for(const file of pending.files){const path=`${cl}/${id}/${record.id}/${crypto.randomUUID()}-${safeName(file.name)}`;try{const hash=await fileHash(file),up=await c.storage.from('mentalita-clinical-attachments').upload(path,file,{contentType:file.type,upsert:false});if(up.error){notify('Não foi possível anexar '+file.name+': '+up.error.message);continue;}const {data,error}=await c.from('mentalita_patient_record_attachments').insert({clinic_id:cl,patient_id:id,record_id:record.id,uploaded_by:u?.id||null,storage_path:path,file_name:file.name,mime_type:file.type,file_size:file.size,file_hash:hash}).select('*').single();if(error){await c.storage.from('mentalita-clinical-attachments').remove([path]);notify('Não foi possível registrar '+file.name);continue;}await audit(record.id,'record_attachment_added',{attachment_id:data.id,file_name:file.name,file_hash:hash,size_bytes:file.size});}catch(e){console.error(e);notify('Erro ao anexar '+file.name);}}pending.files=[];pending.startedAt=null;renderDraft();notify('Anexos vinculados ao registro.');}
  async function captureAfterSave(){if(!document.getElementById('mentalitaProntuarioModal')||!pending.files.length)return;pending.startedAt=new Date().toISOString();for(let i=0;i<10;i++){await new Promise(r=>setTimeout(r,500));const r=await findNewRecord();if(r){await uploadForRecord(r);return;}}notify('O registro foi salvo, mas os anexos não puderam ser vinculados automaticamente.');pending.files=[];pending.startedAt=null;}
  async function list(recordId){const c=client();if(!c||!recordId)return[];const {data}=await c.from('mentalita_patient_record_attachments').select('*').eq('record_id',recordId).order('created_at',{ascending:false});return(data||[]).filter(x=>x.status===undefined||x.status==='active');}
  function panel(recordId){document.getElementById('mpAttachmentModal')?.remove();document.body.insertAdjacentHTML('beforeend',`<div id="mpAttachmentModal" style="position:fixed;inset:0;z-index:10002;background:rgba(0,0,0,.48);display:flex;align-items:center;justify-content:center;padding:16px"><div style="width:min(560px,100%);background:var(--surface,#fff);border-radius:18px;padding:22px;box-shadow:0 24px 70px rgba(0,0,0,.2)"><div style="display:flex;justify-content:space-between;align-items:center"><div><div style="font-size:11px;text-transform:uppercase;letter-spacing:.12em;color:var(--text-secondary);font-weight:800">Anexo clínico</div><h2 style="margin:4px 0">Adicionar arquivo</h2></div><button class="btn" id="mpAttachmentClose">Fechar</button></div><p style="font-size:12px;color:var(--text-secondary)">Arquivo vinculado diretamente a este registro clínico. Limite de 10 MB.</p><input id="mpAttachmentFile" type="file" accept="application/pdf,image/jpeg,image/png" style="width:100%;padding:12px;border:1px solid var(--border);border-radius:10px"><div style="display:flex;justify-content:flex-end;gap:8px;margin-top:16px"><button class="btn btn-primary" id="mpAttachmentUpload">Anexar arquivo</button></div></div></div>`);document.getElementById('mpAttachmentClose').onclick=()=>document.getElementById('mpAttachmentModal')?.remove();document.getElementById('mpAttachmentUpload').onclick=()=>uploadExisting(recordId);}
  async function uploadExisting(recordId){const input=document.getElementById('mpAttachmentFile'),file=input?.files?.[0];if(!file){notify('Selecione um arquivo.');return;}if(!allowed.includes(file.type)||file.size>MAX){notify('Use PDF, JPG ou PNG de até 10 MB.');return;}pending.files=[file];const c=client(),p=patient(),cl=clinic(),u=user(),id=pid(p);const path=`${cl}/${id}/${recordId}/${crypto.randomUUID()}-${safeName(file.name)}`,hash=await fileHash(file),up=await c.storage.from('mentalita-clinical-attachments').upload(path,file,{contentType:file.type,upsert:false});if(up.error){notify('Não foi possível enviar o arquivo.');return;}const {data,error}=await c.from('mentalita_patient_record_attachments').insert({clinic_id:cl,patient_id:id,record_id:recordId,uploaded_by:u?.id||null,storage_path:path,file_name:file.name,mime_type:file.type,file_size:file.size,file_hash:hash}).select('*').single();if(error){await c.storage.from('mentalita-clinical-attachments').remove([path]);notify('Não foi possível registrar o anexo.');return;}await audit(recordId,'record_attachment_added',{attachment_id:data.id,file_name:file.name,file_hash:hash,size_bytes:file.size});pending.files=[];document.getElementById('mpAttachmentModal')?.remove();notify('Anexo clínico adicionado.');if(typeof window.renderPatientProfile==='function')window.renderPatientProfile();}
  async function render(){const root=document.getElementById('mentalitaPatientProntuarioTimeline');if(!root)return;root.querySelectorAll('[data-record-id]').forEach(async card=>{if(card.querySelector('.mpAttachments'))return;const id=card.dataset.recordId;if(!id)return;const files=await list(id);const box=document.createElement('div');box.className='mpAttachments';box.style.cssText='margin-top:12px;padding-top:10px;border-top:1px solid var(--border)';box.innerHTML=`<div style="display:flex;justify-content:space-between;align-items:center;gap:8px"><strong style="font-size:11px">Anexos</strong><button type="button" class="btn mpAddAttachment" data-id="${esc(id)}">+ Adicionar</button></div>${files.length?files.map(f=>`<div style="display:flex;justify-content:space-between;align-items:center;margin-top:8px;font-size:11px"><span>📎 ${esc(f.file_name)} <span style="color:var(--text-secondary)">· ${humanSize(f.file_size)}</span></span><button type="button" class="btn mpOpenAttachment" data-id="${esc(f.id)}">Abrir</button></div>`).join(''):'<div style="font-size:10.5px;color:var(--text-secondary);margin-top:6px">Nenhum anexo clínico.</div>'}`;card.appendChild(box);});}
  async function openAttachment(id){const c=client();if(!c)return;const {data,error}=await c.from('mentalita_patient_record_attachments').select('*').eq('id',id).single();if(error||!data)return;const {data:urlData,error:urlError}=await c.storage.from('mentalita-clinical-attachments').createSignedUrl(data.storage_path,300);if(urlError){notify('Não foi possível abrir o arquivo.');return;}await audit(data.record_id,'record_attachment_viewed',{attachment_id:data.id,file_name:data.file_name});window.open(urlData.signedUrl,'_blank','noopener');}
  function install(){window.__mentalitaProntuarioAnexos=true;const observer=new MutationObserver(()=>{injectDraft();render();});observer.observe(document.body,{childList:true,subtree:true});document.addEventListener('click',e=>{if(e.target.closest?.('#mpDraft')||e.target.closest?.('#mpForm button[type="submit"]')){if(pending.files.length)captureAfterSave();}const a=e.target.closest?.('.mpAddAttachment');if(a){e.preventDefault();panel(a.dataset.id);return;}const o=e.target.closest?.('.mpOpenAttachment');if(o){e.preventDefault();openAttachment(o.dataset.id);}},true);document.addEventListener('submit',e=>{if(e.target?.id==='mpForm'&&pending.files.length)captureAfterSave();},true);}
  install();
})();
