// Mentalita — Anexos clínicos do prontuário
(function installMentalitaProntuarioAnexos(){
  if(window.__mentalitaProntuarioAnexos)return;
  const client=()=>window.PLURI_SUPABASE||null;
  const patient=()=>window.state?.selectedPatient||(typeof state!=='undefined'?state.selectedPatient:null);
  const clinic=()=>window.PLURI_CLINIC?.id||null;
  const user=()=>window.PLURI_AUTH_SESSION?.user||null;
  const pid=p=>p?.id||p?.ID||p?._id||null;
  const esc=v=>typeof patientEscape==='function'?patientEscape(v):String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;');
  const notify=m=>typeof showToast==='function'?showToast(m):console.log('[Mentalita]',m);
  const MAX=10*1024*1024;
  const allowed=['application/pdf','image/jpeg','image/png'];
  async function audit(recordId,action,metadata={}){const c=client(),p=patient(),u=user();if(!c||!clinic()||!pid(p)||!recordId)return;c.from('mentalita_patient_record_audit').insert({clinic_id:clinic(),patient_id:pid(p),record_id:recordId,actor_user_id:u?.id||null,action,occurred_at:new Date().toISOString(),metadata:{...metadata,source:'mentalita-web'}});}
  async function list(recordId){const c=client();if(!c||!recordId)return[];const {data}=await c.from('mentalita_patient_record_attachments').select('*').eq('record_id',recordId).eq('status','active').order('created_at',{ascending:false});return data||[];}
  function humanSize(n){if(!n)return'0 KB';if(n<1024*1024)return`${Math.round(n/1024)} KB`;return`${(n/1024/1024).toFixed(1)} MB`;}
  function panel(recordId){document.getElementById('mpAttachmentModal')?.remove();document.body.insertAdjacentHTML('beforeend',`<div id="mpAttachmentModal" style="position:fixed;inset:0;z-index:10002;background:rgba(0,0,0,.48);display:flex;align-items:center;justify-content:center;padding:16px"><div style="width:min(560px,100%);background:var(--surface,#fff);border-radius:18px;padding:22px;box-shadow:0 24px 70px rgba(0,0,0,.2)"><div style="display:flex;justify-content:space-between;align-items:center"><div><div style="font-size:11px;text-transform:uppercase;letter-spacing:.12em;color:var(--text-secondary);font-weight:800">Anexo clínico</div><h2 style="margin:4px 0">Adicionar arquivo</h2></div><button class="btn" id="mpAttachmentClose">Fechar</button></div><p style="font-size:12px;color:var(--text-secondary)">Arquivo vinculado diretamente a este registro clínico. Limite de 10 MB.</p><input id="mpAttachmentFile" type="file" accept="application/pdf,image/jpeg,image/png" style="width:100%;padding:12px;border:1px solid var(--border);border-radius:10px"><div style="display:flex;justify-content:flex-end;gap:8px;margin-top:16px"><button class="btn btn-primary" id="mpAttachmentUpload">Anexar arquivo</button></div></div></div>`);document.getElementById('mpAttachmentClose').onclick=()=>document.getElementById('mpAttachmentModal')?.remove();document.getElementById('mpAttachmentUpload').onclick=()=>upload(recordId);}
  async function upload(recordId){const c=client(),p=patient(),u=user(),input=document.getElementById('mpAttachmentFile'),file=input?.files?.[0];if(!c||!clinic()||!pid(p)||!recordId||!file){notify('Selecione um arquivo.');return;}if(file.size>MAX){notify('O arquivo ultrapassa o limite de 10 MB.');return;}if(!allowed.includes(file.type)){notify('Formato não permitido. Use PDF, JPG ou PNG.');return;}const safe=file.name.replace(/[^a-zA-Z0-9._-]+/g,'_'),path=`${clinic()}/${pid(p)}/${recordId}/${crypto.randomUUID()}-${safe}`;const {error:up}=await c.storage.from('mentalita-clinical-attachments').upload(path,file,{contentType:file.type,upsert:false});if(up){notify('Não foi possível enviar o arquivo.');console.error(up);return;}const buf=await file.arrayBuffer(),hash=await crypto.subtle.digest('SHA-256',buf),fileHash=Array.from(new Uint8Array(hash)).map(x=>x.toString(16).padStart(2,'0')).join('');const {data,error}=await c.from('mentalita_patient_record_attachments').insert({clinic_id:clinic(),patient_id:pid(p),record_id:recordId,uploaded_by:u?.id||null,original_name:file.name,storage_path:path,mime_type:file.type,size_bytes:file.size,file_hash:fileHash}).select('*').single();if(error){await c.storage.from('mentalita-clinical-attachments').remove([path]);notify('Não foi possível registrar o anexo.');console.error(error);return;}await audit(recordId,'record_attachment_added',{attachment_id:data.id,file_name:file.name,file_hash:fileHash});document.getElementById('mpAttachmentModal')?.remove();notify('Anexo clínico adicionado.');if(typeof window.renderPatientProfile==='function')window.renderPatientProfile();}
  async function render(){const root=document.getElementById('mentalitaPatientProntuarioTimeline');if(!root)return;root.querySelectorAll('[data-record-id]').forEach(async card=>{if(card.querySelector('.mpAttachments'))return;const id=card.dataset.recordId;if(!id)return;const files=await list(id);const box=document.createElement('div');box.className='mpAttachments';box.style.cssText='margin-top:12px;padding-top:10px;border-top:1px solid var(--border)';box.innerHTML=`<div style="display:flex;justify-content:space-between;align-items:center;gap:8px"><strong style="font-size:11px">Anexos</strong><button type="button" class="btn mpAddAttachment" data-id="${esc(id)}">+ Adicionar</button></div>${files.length?files.map(f=>`<div style="display:flex;justify-content:space-between;align-items:center;margin-top:8px;font-size:11px"><span>📎 ${esc(f.original_name)} <span style="color:var(--text-secondary)">· ${humanSize(f.size_bytes)}</span></span><button type="button" class="btn mpOpenAttachment" data-id="${esc(f.id)}">Abrir</button></div>`).join(''):'<div style="font-size:10.5px;color:var(--text-secondary);margin-top:6px">Nenhum anexo clínico.</div>'}`;card.appendChild(box);});}
  async function openAttachment(id){const c=client();if(!c)return;const {data,error}=await c.from('mentalita_patient_record_attachments').select('*').eq('id',id).single();if(error||!data)return;const {data:urlData,error:urlError}=await c.storage.from('mentalita-clinical-attachments').createSignedUrl(data.storage_path,300);if(urlError){notify('Não foi possível abrir o arquivo.');return;}await audit(data.record_id,'record_attachment_viewed',{attachment_id:data.id,file_name:data.original_name});window.open(urlData.signedUrl,'_blank','noopener');}
  function install(){window.__mentalitaProntuarioAnexos=true;const observer=new MutationObserver(render),start=()=>{const root=document.getElementById('mentalitaPatientProntuarioTimeline');if(root)observer.observe(root,{childList:true,subtree:true});render();};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();document.addEventListener('click',e=>{const a=e.target.closest?.('.mpAddAttachment');if(a){e.preventDefault();panel(a.dataset.id);return;}const o=e.target.closest?.('.mpOpenAttachment');if(o){e.preventDefault();openAttachment(o.dataset.id);}},true);}
  install();
})();
